production_unit_mapping = {
    "Integrated_steelworks": "kt",
    "Electric_arc": "kt",
    "Alumina": "kt",
    "Aluminium_primary": "kt",
    "Aluminium_secondary": "kt",
    "Other_non_ferrous": "kt lead eq.",
    "Basic_chemicals": "kt ethylene eq.",
    "Other_chemicals": "kt ethylene eq.",
    "Pharmaceutical_products": "kt ethylene eq.",
    "Cement": "kt",
    "Ceramics_and_other_non_metalic_minerals": "kt bricks eq.",
    "Glass": "kt",
    "Pulp": "kt",
    "Paper": "kt",
    "Printing_and_media": "kt paper eq.",
    "Food_beverages_and_tobacco": "production index",
    "Textile_and_leather": "production index",
    "transport_equipment": "production index",
    "machinery_equipment": "production index",
    "wood_and_wood_products": "production index",
    "other_industrial_sectors": "production index"
}

CO2_unit_mapping = {
    "Integrated_steelworks": "kt CO2",
    "Electric_arc": "kt CO2",
    "Alumina": "kt CO2",
    "Aluminium_primary": "kt CO2",
    "Aluminium_secondary": "kt CO2",
    "Other_non_ferrous": "kt CO2",
    "Basic_chemicals": "kt CO2",
    "Other_chemicals": "kt CO2",
    "Pharmaceutical_products": "kt CO2",
    "Cement": "kt CO2",
    "Ceramics_and_other_non_metalic_minerals": "kt CO2",
    "Glass": "kt CO2",
    "Pulp": "kt CO2",
    "Paper": "kt CO2",
    "Printing_and_media": "kt CO2",
    "Food_beverages_and_tobacco": "kt CO2",
    "Textile_and_leather": "kt CO2",
    "transport_equipment": "kt CO2",
    "machinery_equipment": "kt CO2",
    "wood_and_wood_products": "kt CO2",
    "other_industrial_sectors": "kt CO2"
}

energy_use_unit_mapping = {
    "Integrated_steelworks": "TJ",
    "Electric_arc": "TJ",
    "Alumina": "TJ",
    "Aluminium_primary": "TJ",
    "Aluminium_secondary": "TJ",
    "Other_non_ferrous": "TJ",
    "Basic_chemicals": "TJ",
    "Other_chemicals": "TJ",
    "Pharmaceutical_products": "TJ",
    "Cement": "TJ",
    "Ceramics_and_other_non_metalic_minerals": "TJ",
    "Glass": "TJ",
    "Pulp": "TJ",
    "Paper": "TJ",
    "Printing_and_media": "TJ",
    "Food_beverages_and_tobacco": "TJ",
    "Textile_and_leather": "TJ",
    "transport_equipment": "TJ",
    "machinery_equipment": "TJ",
    "wood_and_wood_products": "TJ",
    "other_industrial_sectors": "TJ"}
